easyadmin:
    resource: .
    type: easyadmin.routes
    prefix: /admin

app_login:
    path: /login
    controller: App\Controller\LoginController::index

controllers_api:
    resource: ../src/Controller/Api/
    type: attribute
    prefix: /api

controllers_admin:
    resource: ../src/Controller/Admin/
    type: attribute
    prefix: /admin
