framework:
    default_locale: en
    enabled_locales: ['en', 'pl']
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
