name: DB
env:
    PHP_VER: '8.4'
    EXTENSIONS: composer
    DATABASE_URL: 'postgresql://admin:root@localhost:5432/blog?serverVersion=16&charset=utf8'
on:
    pull_request:
        paths:
            - 'app/migrations/*.php'
jobs:
    migrations:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USER: admin
                    POSTGRES_PASSWORD: root
                    POSTGRES_DB: blog
                options: >-
                    --health-cmd "pg_isready -U symfony"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.PHP_VER }}
                    tools: ${{ env.EXTENSIONS }}

            -   name: Install dependencies
                run: composer install --no-scripts --prefer-dist --no-interaction
                working-directory: ./app

            - name: Wait for PostgreSQL
              run: |
                  for i in {1..10}; do
                      if pg_isready -h localhost -p 5432 -U admin; then
                          break
                      fi
                      sleep 3
                  done

            - name: Run migrations
              run: |
                  php bin/console doctrine:database:create --if-not-exists
                  php bin/console doctrine:migrations:migrate --no-interaction
              working-directory: ./app
