name: PHP Lint

on:
    pull_request:
        paths:
            - '**/*.php'

jobs:
    phpstan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP 8.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  tools: composer

            - name: Install dependencies
              run: composer install --no-scripts --prefer-dist --no-interaction
              working-directory: ./app

            - name: Run PHPStan
              run: XDEBUG_MODE=off vendor/bin/phpstan --no-interaction
              working-directory: ./app
